export const englishTranslations = {
  navigation: {
    mission: 'Mission',
    gospel: 'Gospel',
    whoAmI: 'Who am I?',
    joinUs: 'Join Us',
  },
  hero: {
    title: 'Being a Woman of Faith',
    subtitle: 'A life full of purpose',
  },
  mission: {
    title: 'Our Mission',
    content1: 'We are women young and old having one thing in common our faith in God through the Lord Jesus, desiring to empower women with wisdom to live a fulfilled life no matter what stage she may found herself.',
    content2: 'Being rooted in Christ our Lord we want to bring light into the darkness of this world to help our fellow women live a life by faith. For we walk by faith and not by sight.',
    content3: 'Our strength comes from the Lord, so in Him we trust and we hope our content will bless and richly empower you!',
  },
  gospel: {
    title: 'The Gospel of Jesus',
    content1: 'We acknowledge that we cannot do anything on our own and that any power to do good comes from God. Jesus died to reunite us to God and renders one to be born again and be as a living sacrifice unto God.',
    content2: 'We are born sold to sin and slave to sin and we cannot be freed from sin without Christ. Whatever good thing God ask us to do is after we have been regenerated that we can do it fully.',
    content3: 'You are a child of God when you are regenerated by His spirit which leads you to obedience 1 Peter 1:1-2.',
    content4: 'Jesus our Lord has gotten victory over sin and over any dominion or authority in this world so we walk in this victory daily.',
    content5: 'This is the foundation of our work and the source of any strength to do any advice you will find in this website. We hope you begin from this foundation as you follow us.',
  },
  teenagers: {
    welcome: {
      title: "Welcome, Dear Teenager",
      description: "You are at a pivotal point in your life, standing between childhood and womanhood. This is a special time filled with opportunities for growth and discovery."
    },
    sections: {
      introduction: {
        title: "Introduction",
        subtitle: "Your Special Time of Growth",
        content: [
          "You are at a pivotal point in your life, standing between childhood and womanhood. The decisions you make now can have a significant impact on your future.",
          "You are full of energy and, for many, still under parental care. Surrounded by friends, this is a time when a lot can happen.",
          "This is a unique period in your life filled with opportunities and challenges. Let's explore how to navigate this time with wisdom and grace."
        ]
      },
      spirituality: {
        title: "Your Spirituality",
        subtitle: "Finding Your Identity in Christ",
        content: [
          "This is the genesis of your identity. Without a spiritual foundation, you may face physical and mental challenges. You were created by a loving God who desires to make you His daughter. He has already paid the ultimate sacrifice for you.",
          "Will you open your heart and accept the sacrifice of Jesus? Will you give Him full control over your will?",
          "If your identity is in Christ, you will not be swayed by seasonal or societal changes because you will know who you are. You will understand the greatness of your Heavenly Father and how precious you are to Him.",
          "The decision to follow Him and learn about Him through His Word (the Bible) and prayer is a significant step in your life, and it is beneficial to make this commitment while you are still a teenager."
        ]
      },
      physicalHealth: {
        title: "Physical Health",
        subtitle: "Understanding Your Body's Changes",
        content: [
          "You are at a point where many changes are occurring in a phase called puberty. Your appearance becomes more feminine, and here's what you need to know:",
          "• First, don't panic! All changes are normal—you're not alone, we all went through this",
          "• You're growing taller than your male peers, and that's completely normal. This growth spurt will slow down by age 16",
          "• Your breasts are starting to develop, so you might need a bra to feel more comfortable and presentable",
          "• Your biological clock is starting with menstruation. Let your mom know when it happens and use a calendar app to track your cycle",
          "• Your daily calorie requirement has increased to 2200 calories. Focus on essential nutrients like calcium, iron, zinc, and vitamin D",
          "• Balance your diet with dairy and green veggies while limiting candies, fast food, and sodas",
          "• Stay physically active and balance screen time with sports, reading, and household chores"
        ]
      },
      mentalHealth: {
        title: "Mental Health",
        subtitle: "Nurturing Your Mind and Spirit",
        content: [
          "Your mind is going through many transformations as you experience numerous changes and challenges while your brain is still maturing.",
          "If you feel anxious, have trouble sleeping, or feel sad, don't keep it to yourself — talk to God about your feelings and open up to a trusted parent.",
          "Fill your mind with God's word, not the lies of the enemy.",
          "In today's world of social media and peer pressure, comparison and low self-esteem can become significant problems. Remember, you were created uniquely by your heavenly father for a purpose in Christ.",
          "Trust that all things work together for your good, and remember that God, your heavenly father, is aware of everything happening in your life."
        ]
      },
      practicalGuidance: {
        title: "Practical Steps",
        subtitle: "Making the Most of This Season",
        content: [
          "Focus on Your Education:",
          "• Your brain is at a stage where learning comes easily",
          "• Make the most of it and do your best in your studies",
          "",
          "Seek a Good Relationship with God:",
          "• Use these relatively stress-free years to know God more",
          "• Study His Word (the Bible) and pray regularly",
          "• Desire to please Him in everything you do",
          "",
          "Be Close to Your Parents:",
          "• No one on earth can love you more than your parents",
          "• Confide in them about your emotional and physical struggles",
          "• Don't rely on age mates as counselors—they're as inexperienced as you",
          "",
          "Choose the Right Friends:",
          "• Surround yourself with Christian friends who share your goals",
          "• Avoid friends who make you feel inferior",
          "• Don't rush into things meant for the future",
          "",
          "Develop Your Talents:",
          "• Explore activities like music, art, sports, or writing",
          "• Keep yourself productively occupied after school"
        ]
      }
    }
  },
  categories: {
    teenager: {
      title: 'Teenager',
      description: 'Navigate your faith journey during these transformative years',
    },
    youngWoman: {
      title: 'Young Woman',
      description: "Discover God's purpose for your single season",
      welcome: {
        title: 'Welcome, Dear Young Woman',
        description: "This is a special season of preparation and growth. Let's discover God's purpose for your life together."
      },
      sections: {
        identity: {
          title: 'Your Identity in Christ',
          subtitle: 'Understanding Your True Worth',
          content: [
            "You aren't yet married and are preparing yourself for that stage of life while honing other areas. You may still be under parental care or, for many, already independent.",
            'This moment is crucial as it prepares you for marital life, independence, motherhood, and increased responsibility.',
            'Your identity is not defined by marriage or career but by being a daughter of the Most High God. Keep this in mind as we move forward.',
          ]
        },
        journey: {
          title: 'Your Journey',
          subtitle: "Walking in God's Timing",
          content: [
            "You may be completing your studies or already starting a career, and these may occupy most of your days. However, it doesn't end there.",
            'Remember that there is no lateness in any of these areas —education, marriage, or motherhood. As long as you are making the most of the opportunities presented to you, just keep moving forward with confidence.',
            'Our society has diverse views on these matters, but in this forum, we aim to uphold a more godly standard.',
          ]
        },
        rebecca: {
          title: 'Learning from Rebecca',
          subtitle: 'A Story of Faith and Obedience',
          content: [
            'Rebecca (Genesis 24) was a young lady like you, living under parental care. Her behavior and good heart stand out in her story.',
            "She wasn't fetching water to be noticed; it was simply a household chore she was doing. She decided to fetch water for all the camels and even proposed them to come over to their house.",
            'In the process of obeying her parents (doing the will of God), she applied what she had learned from her parents and from God, and she obtained a husband—the only son of Abraham, the father of faith.',
            "You are not late in the eyes of God; He is preparing you for what He has in store for you. You need preparation for any task, so don't go through it with bitterness, but with joy through faith.",
          ]
        },
        dina: {
          title: 'Learning from Dina',
          subtitle: 'Understanding the Dangers of Idleness',
          content: [
            "Dina's story (Genesis 34) teaches us about the dangers of distraction and idleness.",
            'Unlike Rebecca who was diligent in her duties, Dina left her house aimlessly to see the city girls.',
            'The lesson here is clear: stay busy doing what God has given you to do. By doing so, you are learning and equipping yourself with the tools needed for your future duties.',
            "The devil uses idleness and distraction to lead young ladies astray. He does not come just to steal, but also to kill and destroy—don't give him access to any part of your life.",
          ]
        },
        purity: {
          title: 'Sexual Purity',
          subtitle: 'Guarding Your Heart and Body',
          content: [
            'Sexual purity goes beyond physical abstinence—it encompasses your thoughts and activities.',
            'If you are a Christian, you understand that our mind is a major gateway for sin. Sexual purity requires abstaining from any activity or thought which is sexually impure.',
            'Even if you came to know the Lord after losing your virginity or experiencing trauma, you can still become sexually pure. You are a new creature in Christ Jesus (1 Corinthians 5:12).',
            'We are required to offer ourselves as a living sacrifice unto God (Romans 12:1). God wants your body, soul, and mind to belong to Him wholly.',
          ]
        }
      }
    },
    marriedWoman: {
      title: 'Married Women',
      description: 'Build a Christ-centered marriage and home',
      welcome: {
        title: 'Welcome, Dear Sister in Christ',
        description: "Let's discover how to build a Christ-centered marriage and home, walking in faith and purpose."
      },
      sections: {
        introduction: {
          title: 'Introduction',
          subtitle: 'Your Journey as a Married Woman',
          content: [
            "You are married, maybe to a Christian partner or maybe not. You have kids or are planning to have. You are a spouse, mother, daughter in law, sister inlaw etc. That's a lot to manage if you have to do it with your own understanding.",
            'God who gave you these duties did not leave you alone thankfully, he gave you his Holy Spirit to guide you to fulfill this purpose beautifully.',
            'We want to use this platform to show you how to use the tools God has already given you to win your various battles, excel in your duties and live a happy and fulfilled life.',
          ]
        },
        identity: {
          title: 'Who Are You?',
          subtitle: 'Understanding Your True Identity',
          content: [
            "It's true we spoke about being a spouse, a mother, daughter inlaw etc but that's not your identity, those are your roles.",
            "You have to redefine who you are, you are a daughter of the Most High God if you have already surrendered your life to Jesus and have been regenerated by His spirit. If not, please start from there, you can't do it with just rules of do's and don'ts. It's a crucial step for every human being.",
            "You are created in Christ to fulfill the purpose for which God has already planned for you. 'Ephesians 2:9-10'",
          ]
        },
        meaning: {
          title: 'What Does It Mean?',
          subtitle: "Living in God's Purpose",
          content: [
            'Being a woman created in Christ to fulfill the good works which God has already planned for you entails you are not creating what you need to do. You are just entering the plan of God and obeying everything you find there.',
            'In your life you are full of faith that whatever you have before you has been prepared by your Father, so he has your back. It creates assurance and internal peace.',
            'Situations do not shake you, you seem unbothered by the hardest situations not because you are strong but because He that is in you is bigger than he who is out there.',
            'Fear is not your portion, you walk by faith because to you all what your Father has told you through His Word, revelations are true and all other thoughts or words are lies.',
          ]
        },
        marriage: {
          title: 'Living with Your Spouse',
          subtitle: 'Understanding the Marriage Covenant',
          content: [
            "Your spouse is your closest relationship, he knows you more and you are more sensitive towards him. His appreciations or reproaches have more importance to you than anyone else's.",
            'This is just a narrative for most married women, some live different realities, some live at the verge of separation, some even regret to have accepted such a man as spouse.',
            "Here is the common denominator: you are tied to this man as long as he is alive and your union is not just recognized by men but it's a covenant before God which no man can set apart, not even you.",
            "The Bible teaches us the order in marriage in 1 Corinthians 11:3, Christ is the head of the man and man is the head of the woman. So your husband is your head, he leads the home and that's something you should accept wholeheartedly.",
          ]
        },
        submission: {
          title: 'Biblical Submission',
          subtitle: "Walking in God's Order",
          content: [
            'The Bible says he is to love you as Christ loves the church and you are to be submitted to him in everything (Ephesians 5:22-25).',
            'Notice that this command is given to each spouse and was not conditional on the other. Submission is not in case the wife is loved though it will be done more easily in such a case.',
            'But submission is your duty as a wife independent of the obedience of your spouse to his own command to love you.',
            'You may be married to a husband who is not born again; remember you still have to be submitted to him. We will understand as we move why this foundation is important in our walk by faith.',
          ]
        },
        faithWalk: {
          title: 'Living with Your Spouse by Faith',
          subtitle: "Walking in God's Program",
          content: [
            'You have placed the foundation on which your home is built. Now what next? Remember your marriage, or your duty as a spouse is all in the program of God when you are born in Christ.',
            "You know God has good plans for you, plans to make you prosper, so it doesn't matter the look of things in a situation, it will turn out for your good. When we walk by faith, we walk by obedience to his word because we depend on Him entirely. When we walk in obedience our hearts do not condemn us so we can continue to trust in His word.",
            "So even if a misunderstanding arrives with your husband all you have to do is to obey God's word for you at the point: Is it to stay calm, is it to ask for forgiveness, is it to forgive? Just do it and he will accomplish his word for the rest and peace will be back to your home.",
            'Is there an issue with your spouse you find it difficult to bring up the topic, go to his head (God) and ask him to give you wisdom or ask Him to bring the heart of your spouse back to Him in case he is sliding away.',
            'You are not alone in your marriage, your father is with you. So walk by faith with Him through this.',
          ]
        },
        emotions: {
          title: 'The Danger of Walking with Emotions',
          subtitle: 'Choosing Faith Over Feelings',
          content: [
            "We've spoken about walking by faith with your spouse, but let's look at the other way around which is walking by emotions. Emotions is a big part of our couple life, it comprises the romance and everything related. But that should not be the source of our driving force.",
            "If we are led by our emotions it becomes a great danger and can be an open door to your common enemy. Our emotions can't enable us to know the perfect will of God and leads us to walk in the flesh.",
            "That's why in every situation no matter how chaotic it has been we need to stop and get out of the emotion felt to ask God His will. If you are in a hot argument with your spouse, if you're acting by the flesh you will speak your mind as they say, and end up destroying the trust and peace in your couple. Emotions can lead us astray.",
            "Let's speak about a woman in the bible who because she was lead by her emotions let her husband to go against the will of God and till today the consequence still troubles the world.",
          ]
        }
      }
    },
  },
  contact: {
    title: 'Have any questions?',
    description: "Feel free to write to us - we'll be delighted to answer you as the Lord leads us.",
    button: 'Contact Us',
    form: {
      title: 'Contact Us',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'your.email@example.com',
      messagePlaceholder: 'How can we help you?',
      sending: 'Sending...',
      send: 'Send Message',
      success: 'Success!',
      successMessage: "Your message has been sent. We'll get back to you soon!",
      error: 'Error',
      errorMessage: 'Failed to send message. Please try again.',
      validationError: 'Validation Error',
      fillFields: 'Please fill in all fields',
      invalidEmail: 'Invalid Email',
      invalidEmailMessage: 'Please enter a valid email address',
    },
  },
};
