import React from 'react';

const MarriedWomenSpace = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-green-50 text-gray-800 p-8">
      <h1 className="text-4xl font-bold mb-6">Married Women Space</h1>
      <p className="text-lg mb-4">
        Welcome to the Married Women Space! Here you can find resources to build a Christ-centered marriage and home.
      </p>
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-semibold mb-4">Resources for Married Women</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>Bible study guides for couples</li>
          <li>Christian marriage counseling resources</li>
          <li>Devotionals for married life</li>
          <li>Parenting advice from a faith perspective</li>
        </ul>
      </div>
      <div className="bg-white rounded-lg shadow-md p-6 mt-6">
        <h2 className="text-2xl font-semibold mb-4">Being a Married Woman of Faith</h2>
        <div className="space-y-4">
          <h3 className="text-xl font-semibold">Introduction</h3>
          <p>You are married, maybe to a Christian partner or maybe not. You have kids or are planning to have. You are a spouse, mother, daughter-in-law, sister-in-law, etc. That's a lot to manage if you have to do it with your own understanding. God who gave you these duties did not leave you alone thankfully, he gave you his Holy Spirit to guide you to fulfill this purpose beautifully. We want to use this platform to show you how to use the tools God has already given you to win your various battles, excel in your duties and live a happy and fulfilled life.</p>
          
          <h3 className="text-xl font-semibold mt-4">Who are you?</h3>
          <ul className="list-disc pl-5 space-y-2">
            <li>It's true we spoke about being a spouse, a mother, daughter-in-law etc but that's not your identity, those are your roles.</li>
            <li>You have to redefine who you are, you are a daughter of the Most High God if you have already surrendered your life to Jesus and have been regenerated by His spirit. If not, please start from there, you can't do it with just rules of do's and don'ts. It's a crucial step for every human being.</li>
            <li>You are created in Christ to fulfill the purpose for which God has already planned for you. "Ephesians 2:9-10"</li>
          </ul>
          
          <h3 className="text-xl font-semibold mt-4">What does it mean?</h3>
          <ul className="list-disc pl-5 space-y-2">
            <li>Being a woman created in Christ to fulfill the good works which God has already planned for you entails you are not creating what you need to do. You are just entering the plan of God and obeying to everything you find there.</li>
            <li>In your life you are full of faith that whatever you have before you has been prepared by your Father, so he has your back. It creates assurance and internal peace.</li>
            <li>Situations do not shake you, you seem unbothered by the hardest situations not because you are strong but because He that is in you is bigger than he who is out there.</li>
            <li>Fear is not your portion, you walk by faith because to you all what your Father has told you through His Word, revelations are true and all other thoughts or words are lies.</li>
          </ul>
          
          <h3 className="text-xl font-semibold mt-4">Living with your spouse</h3>
          <p>Your spouse is your closest relationship, he knows you more and you are more sensitive towards him. His appreciations or reproaches have more importance to you than anyone else's. You love and cherish him and have a lot of expectations from Him. This is just a narrative for most married women, some live different realities, some live at the verge of separation, some even regret to have accepted such a man as spouse.</p>
          <p>Here is the common denominator, you are tied to this man as long as he is alive and your union is not just recognized by men but it's a covenant before God which no man can set apart not even you. The bible teaches us the order in marriage in 1 Corinthians 11:3, Christ is the head of the man and man is the head of the woman. So your husband is your head, he leads the home and that's something you should accept wholeheartedly.</p>
          
          <h3 className="text-xl font-semibold mt-4">Living with your spouse (2)</h3>
          <ul className="list-disc pl-5 space-y-2">
            <li>The bible says he is to love you as Christ loves the church and you are to be submitted to him in everything Ephesians 5:22-25</li>
            <li>Notice that this command is given to each spouse and was not conditional on the other. Submission is not in case the wife is loved though it will be done more easily in such a case. But submission is your duty as a wife independent of the obedience of your spouse to his own command to love you.</li>
            <li>You may be married to a husband who is not born again remember you still have to be submitted to him we will understand as we move why this foundation is important in our walk by faith.</li>
          </ul>
          
          <h3 className="text-xl font-semibold mt-4">Living with your spouse by faith</h3>
          <p>You have placed the foundation on which your home is built. Now what next? Remember your marriage, or your duty as a spouse is all in the program of God when you are born in Christ. Let's look at a woman in the bible who walked according to her calculations and emotions: Sara.</p>
        </div>
      </div>
    </div>
  );
};

export default MarriedWomenSpace;
